# Site settings
title: Lodeup Engineering Blog
# email: 
description: > # this means to ignore newlines until "baseurl:"
  Geolode is a service for mobile developers to simplify user-to-user
  interactions. The service provides geo-location and user interaction
  APIs to help mobile developers find and interact with nearby users 
  and entities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://engineering.lodeup.com" # the base hostname & protocol for your site
twitter_username: lodeup
github_username:  lodeup

# Build settings
markdown: kramdown

kramdown:
  input: GFM