# Site settings
title: Lodeup Engineering Blog
# email: 
description: > # this means to ignore newlines until "baseurl:"
  Geolode is a service for mobile developers to simplify user-to-user
  interactions. The service provides geo-location and user interaction
  APIs to help mobile developers find and interact with nearby users 
  and entities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://engineering.lodeup.com" # the base hostname & protocol for your site
twitter_username: lodeup
github_username:  lodeup

# Build settings
markdown: kramdown

kramdown:
  input: GFM

paginate: 5

author: Lodeup

twitter:
  username:            lodeup             # Add your Twitter handle
  tweet_count:         false              # Show number of shares on Twitter
  size:                normal             # Or large
  embedded_link_color:                    # Set link color for embedded tweets

  follow_count:        false              # Show number of followers
  tweet_message:       ":title by :username :hashtags - :url" # With Tweet button Twitter add the URL last
  tweet_link_text:     Twitter            # Configure the link text
  tweet_link_title:    Share on Twitter   # Share link title
  profile_link_text:   Follow :username
  profile_link_title:  Follow :username on Twitter  # Profile link title text